# fly.toml file generated for udp-service on 2023-04-05T18:33:56-04:00

app = "echo-udp"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []
primary_region = "ewr"

[build]
  dockerfile = "Dockerfile"

[[services]]
  protocol = "udp"
  internal_port = 5002

  [[services.ports]]
    port = 5002

[experimental]
  allowed_public_ports = []
  auto_rollback = true
